spring.application.name=JCampaign

#false so that transactions aren't opened during request processing
spring.jpa.open-in-view=false

#false because we don't want to acquire the connection when the transactional method is entered, but when the connection is first needed.
spring.datasource.hikari.auto-commit=false

spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.enabled=true


flowable.process.definition-cache-limit=20

spring.modulith.events.republish-outstanding-events-on-restart=true